import os

DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL")
GOOGLE_SERVICE_ACCOUNT_JSON = os.getenv("GOOGLE_SERVICE_ACCOUNT_JSON")
GOOGLE_SHEET_CARDS_NAME = os.getenv("GOOGLE_SHEET_CARDS_NAME")

EBAY_CLIENT_ID = os.getenv("EBAY_CLIENT_ID")
EBAY_CLIENT_SECRET = os.getenv("EBAY_CLIENT_SECRET")
EBAY_MARKETPLACE_ID = os.getenv("EBAY_MARKETPLACE_ID", "EBAY_US")

EBAY_CONCURRENT_REQUESTS = int(os.getenv("EBAY_CONCURRENT_REQUESTS", 5))
BATCH_DELAY_SECONDS = int(os.getenv("BATCH_DELAY_SECONDS", 30))
