import os

# Google Sheet
GOOGLE_SHEET_CARDS_NAME = os.getenv("GOOGLE_SHEET_CARDS_NAME")
GOOGLE_SERVICE_ACCOUNT_JSON = os.getenv("GOOGLE_SERVICE_ACCOUNT_JSON")

# eBay API
EBAY_CLIENT_ID = os.getenv("EBAY_CLIENT_ID")
EBAY_CLIENT_SECRET = os.getenv("EBAY_CLIENT_SECRET")
EBAY_MARKETPLACE_ID = os.getenv("EBAY_MARKETPLACE_ID")

# Discord
DISCORD_WEBHOOK_URL = os.getenv("DISCORD_WEBHOOK_URL")

# Concurrency
EBAY_CONCURRENT_REQUESTS = int(os.getenv("EBAY_CONCURRENT_REQUESTS", 5))
BATCH_DELAY_SECONDS = int(os.getenv("BATCH_DELAY_SECONDS", 300))  # 5 min
